

default: &default
  config:
    secret_key_base: 895c28d0116e7e7ba8e25c8d547d512448deef94f5f7aa5d2386744f25f34b1b586e3e481b3b831f72f9ea54d06cc84bc61b53e6b7d6272f1f6d00b47c0da41f
    registerable: false
    mailer_sender: noreply@beacon-os.com
    mailer_url_options:
      host: localhost
      port: 3000
    smtp_settings:
      address: smtp.gmail.com
      port: 587
      domain: beacon-os.com
      user_name: noreply@beacon-os.com
      password: 
      authentication: plain
      enable_starttls_auto: false
    system_mailer_receiver: noreply@beacon-os.com
    redis_url: redis://localhost:6379
    create_test_app_on_new_account: false
    autoload_extensions:
      "Analytics":  false
      "DwellTime":  false
      "Kontakt.io": false
      "Presence":   false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
